// Copyright (c) 2022 Alibaba Group Holding Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: networking/v1/http_2_rpc.proto

// $schema: higress.networking.v1.Http2Rpc
// $title: Http2Rpc
// $description: Configuration affecting service discovery from multi registries
// $mode: none

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// <!-- crd generation tags
// +cue-gen:Http2Rpc:groupName:networking.higress.io
// +cue-gen:Http2Rpc:version:v1
// +cue-gen:Http2Rpc:storageVersion
// +cue-gen:Http2Rpc:annotations:helm.sh/resource-policy=keep
// +cue-gen:Http2Rpc:subresource:status
// +cue-gen:Http2Rpc:scope:Namespaced
// +cue-gen:Http2Rpc:resource:categories=higress-io,plural=http2rpcs
// +cue-gen:Http2Rpc:preserveUnknownFields:false
// -->
//
// <!-- go code generation tags
// +kubetype-gen
// +kubetype-gen:groupVersion=networking.higress.io/v1
// +genclient
// +k8s:deepcopy-gen=true
// -->
type Http2Rpc struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Destination:
	//
	//	*Http2Rpc_Dubbo
	//	*Http2Rpc_Grpc
	Destination   isHttp2Rpc_Destination `protobuf_oneof:"destination"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Http2Rpc) Reset() {
	*x = Http2Rpc{}
	mi := &file_networking_v1_http_2_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Http2Rpc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Http2Rpc) ProtoMessage() {}

func (x *Http2Rpc) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1_http_2_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Http2Rpc.ProtoReflect.Descriptor instead.
func (*Http2Rpc) Descriptor() ([]byte, []int) {
	return file_networking_v1_http_2_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *Http2Rpc) GetDestination() isHttp2Rpc_Destination {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *Http2Rpc) GetDubbo() *DubboService {
	if x != nil {
		if x, ok := x.Destination.(*Http2Rpc_Dubbo); ok {
			return x.Dubbo
		}
	}
	return nil
}

func (x *Http2Rpc) GetGrpc() *GrpcService {
	if x != nil {
		if x, ok := x.Destination.(*Http2Rpc_Grpc); ok {
			return x.Grpc
		}
	}
	return nil
}

type isHttp2Rpc_Destination interface {
	isHttp2Rpc_Destination()
}

type Http2Rpc_Dubbo struct {
	Dubbo *DubboService `protobuf:"bytes,1,opt,name=dubbo,proto3,oneof"`
}

type Http2Rpc_Grpc struct {
	Grpc *GrpcService `protobuf:"bytes,2,opt,name=grpc,proto3,oneof"`
}

func (*Http2Rpc_Dubbo) isHttp2Rpc_Destination() {}

func (*Http2Rpc_Grpc) isHttp2Rpc_Destination() {}

type DubboService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Methods       []*Method              `protobuf:"bytes,4,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DubboService) Reset() {
	*x = DubboService{}
	mi := &file_networking_v1_http_2_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DubboService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DubboService) ProtoMessage() {}

func (x *DubboService) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1_http_2_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DubboService.ProtoReflect.Descriptor instead.
func (*DubboService) Descriptor() ([]byte, []int) {
	return file_networking_v1_http_2_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *DubboService) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *DubboService) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DubboService) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *DubboService) GetMethods() []*Method {
	if x != nil {
		return x.Methods
	}
	return nil
}

type Method struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ServiceMethod       string                 `protobuf:"bytes,1,opt,name=service_method,json=serviceMethod,proto3" json:"service_method,omitempty"`
	HeadersAttach       string                 `protobuf:"bytes,2,opt,name=headers_attach,json=headersAttach,proto3" json:"headers_attach,omitempty"`
	HttpPath            string                 `protobuf:"bytes,3,opt,name=http_path,json=httpPath,proto3" json:"http_path,omitempty"`
	HttpMethods         []string               `protobuf:"bytes,4,rep,name=http_methods,json=httpMethods,proto3" json:"http_methods,omitempty"`
	Params              []*Param               `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty"`
	ParamFromEntireBody *ParamFromEntireBody   `protobuf:"bytes,6,opt,name=paramFromEntireBody,proto3" json:"paramFromEntireBody,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Method) Reset() {
	*x = Method{}
	mi := &file_networking_v1_http_2_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Method) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Method) ProtoMessage() {}

func (x *Method) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1_http_2_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Method.ProtoReflect.Descriptor instead.
func (*Method) Descriptor() ([]byte, []int) {
	return file_networking_v1_http_2_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *Method) GetServiceMethod() string {
	if x != nil {
		return x.ServiceMethod
	}
	return ""
}

func (x *Method) GetHeadersAttach() string {
	if x != nil {
		return x.HeadersAttach
	}
	return ""
}

func (x *Method) GetHttpPath() string {
	if x != nil {
		return x.HttpPath
	}
	return ""
}

func (x *Method) GetHttpMethods() []string {
	if x != nil {
		return x.HttpMethods
	}
	return nil
}

func (x *Method) GetParams() []*Param {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Method) GetParamFromEntireBody() *ParamFromEntireBody {
	if x != nil {
		return x.ParamFromEntireBody
	}
	return nil
}

type Param struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParamSource   string                 `protobuf:"bytes,1,opt,name=param_source,json=paramSource,proto3" json:"param_source,omitempty"`
	ParamKey      string                 `protobuf:"bytes,2,opt,name=param_key,json=paramKey,proto3" json:"param_key,omitempty"`
	ParamType     string                 `protobuf:"bytes,3,opt,name=param_type,json=paramType,proto3" json:"param_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Param) Reset() {
	*x = Param{}
	mi := &file_networking_v1_http_2_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Param) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Param) ProtoMessage() {}

func (x *Param) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1_http_2_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Param.ProtoReflect.Descriptor instead.
func (*Param) Descriptor() ([]byte, []int) {
	return file_networking_v1_http_2_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *Param) GetParamSource() string {
	if x != nil {
		return x.ParamSource
	}
	return ""
}

func (x *Param) GetParamKey() string {
	if x != nil {
		return x.ParamKey
	}
	return ""
}

func (x *Param) GetParamType() string {
	if x != nil {
		return x.ParamType
	}
	return ""
}

type ParamFromEntireBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParamType     string                 `protobuf:"bytes,1,opt,name=param_type,json=paramType,proto3" json:"param_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamFromEntireBody) Reset() {
	*x = ParamFromEntireBody{}
	mi := &file_networking_v1_http_2_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamFromEntireBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamFromEntireBody) ProtoMessage() {}

func (x *ParamFromEntireBody) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1_http_2_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamFromEntireBody.ProtoReflect.Descriptor instead.
func (*ParamFromEntireBody) Descriptor() ([]byte, []int) {
	return file_networking_v1_http_2_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *ParamFromEntireBody) GetParamType() string {
	if x != nil {
		return x.ParamType
	}
	return ""
}

type GrpcService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcService) Reset() {
	*x = GrpcService{}
	mi := &file_networking_v1_http_2_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcService) ProtoMessage() {}

func (x *GrpcService) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1_http_2_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcService.ProtoReflect.Descriptor instead.
func (*GrpcService) Descriptor() ([]byte, []int) {
	return file_networking_v1_http_2_rpc_proto_rawDescGZIP(), []int{5}
}

var File_networking_v1_http_2_rpc_proto protoreflect.FileDescriptor

const file_networking_v1_http_2_rpc_proto_rawDesc = "" +
	"\n" +
	"\x1enetworking/v1/http_2_rpc.proto\x12\x15higress.networking.v1\x1a\x1fgoogle/api/field_behavior.proto\"\x90\x01\n" +
	"\bHttp2Rpc\x12;\n" +
	"\x05dubbo\x18\x01 \x01(\v2#.higress.networking.v1.DubboServiceH\x00R\x05dubbo\x128\n" +
	"\x04grpc\x18\x02 \x01(\v2\".higress.networking.v1.GrpcServiceH\x00R\x04grpcB\r\n" +
	"\vdestination\"\xa9\x01\n" +
	"\fDubboService\x12\x1e\n" +
	"\aservice\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\aservice\x12\x1e\n" +
	"\aversion\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\aversion\x12\x1a\n" +
	"\x05group\x18\x03 \x01(\tB\x04\xe2A\x01\x01R\x05group\x12=\n" +
	"\amethods\x18\x04 \x03(\v2\x1d.higress.networking.v1.MethodB\x04\xe2A\x01\x02R\amethods\"\xc8\x02\n" +
	"\x06Method\x12+\n" +
	"\x0eservice_method\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\rserviceMethod\x12+\n" +
	"\x0eheaders_attach\x18\x02 \x01(\tB\x04\xe2A\x01\x01R\rheadersAttach\x12!\n" +
	"\thttp_path\x18\x03 \x01(\tB\x04\xe2A\x01\x02R\bhttpPath\x12'\n" +
	"\fhttp_methods\x18\x04 \x03(\tB\x04\xe2A\x01\x02R\vhttpMethods\x124\n" +
	"\x06params\x18\x05 \x03(\v2\x1c.higress.networking.v1.ParamR\x06params\x12b\n" +
	"\x13paramFromEntireBody\x18\x06 \x01(\v2*.higress.networking.v1.ParamFromEntireBodyB\x04\xe2A\x01\x01R\x13paramFromEntireBody\"x\n" +
	"\x05Param\x12'\n" +
	"\fparam_source\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\vparamSource\x12!\n" +
	"\tparam_key\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\bparamKey\x12#\n" +
	"\n" +
	"param_type\x18\x03 \x01(\tB\x04\xe2A\x01\x02R\tparamType\":\n" +
	"\x13ParamFromEntireBody\x12#\n" +
	"\n" +
	"param_type\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\tparamType\"\r\n" +
	"\vGrpcServiceB1Z/github.com/alibaba/higress/v2/api/networking/v1b\x06proto3"

var (
	file_networking_v1_http_2_rpc_proto_rawDescOnce sync.Once
	file_networking_v1_http_2_rpc_proto_rawDescData []byte
)

func file_networking_v1_http_2_rpc_proto_rawDescGZIP() []byte {
	file_networking_v1_http_2_rpc_proto_rawDescOnce.Do(func() {
		file_networking_v1_http_2_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_networking_v1_http_2_rpc_proto_rawDesc), len(file_networking_v1_http_2_rpc_proto_rawDesc)))
	})
	return file_networking_v1_http_2_rpc_proto_rawDescData
}

var file_networking_v1_http_2_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_networking_v1_http_2_rpc_proto_goTypes = []any{
	(*Http2Rpc)(nil),            // 0: higress.networking.v1.Http2Rpc
	(*DubboService)(nil),        // 1: higress.networking.v1.DubboService
	(*Method)(nil),              // 2: higress.networking.v1.Method
	(*Param)(nil),               // 3: higress.networking.v1.Param
	(*ParamFromEntireBody)(nil), // 4: higress.networking.v1.ParamFromEntireBody
	(*GrpcService)(nil),         // 5: higress.networking.v1.GrpcService
}
var file_networking_v1_http_2_rpc_proto_depIdxs = []int32{
	1, // 0: higress.networking.v1.Http2Rpc.dubbo:type_name -> higress.networking.v1.DubboService
	5, // 1: higress.networking.v1.Http2Rpc.grpc:type_name -> higress.networking.v1.GrpcService
	2, // 2: higress.networking.v1.DubboService.methods:type_name -> higress.networking.v1.Method
	3, // 3: higress.networking.v1.Method.params:type_name -> higress.networking.v1.Param
	4, // 4: higress.networking.v1.Method.paramFromEntireBody:type_name -> higress.networking.v1.ParamFromEntireBody
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_networking_v1_http_2_rpc_proto_init() }
func file_networking_v1_http_2_rpc_proto_init() {
	if File_networking_v1_http_2_rpc_proto != nil {
		return
	}
	file_networking_v1_http_2_rpc_proto_msgTypes[0].OneofWrappers = []any{
		(*Http2Rpc_Dubbo)(nil),
		(*Http2Rpc_Grpc)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_networking_v1_http_2_rpc_proto_rawDesc), len(file_networking_v1_http_2_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_networking_v1_http_2_rpc_proto_goTypes,
		DependencyIndexes: file_networking_v1_http_2_rpc_proto_depIdxs,
		MessageInfos:      file_networking_v1_http_2_rpc_proto_msgTypes,
	}.Build()
	File_networking_v1_http_2_rpc_proto = out.File
	file_networking_v1_http_2_rpc_proto_goTypes = nil
	file_networking_v1_http_2_rpc_proto_depIdxs = nil
}
